(()=>{
'use strict';
const KEY='irish-player-iq-final-qa3';
let roster=[],schedule=[],history=[],photoMap={},syncStatus={};
let state=loadState();
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const shuffle=a=>{const x=[...a];for(let i=x.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[x[i],x[j]]=[x[j],x[i]]}return x};
const uniq=a=>[...new Set(a)];
const MODES=['numberPlayer','playerNumber','playerPosition','photoPlayer','photoNumber','photoPosition','hidden'];
function loadState(){try{return Object.assign(defaultState(),JSON.parse(localStorage.getItem(KEY)||'{}'))}catch{return defaultState()}}
function defaultState(){return {view:'home',progressTab:'players',gameMode:'mix',question:0,round:10,score:0,streak:0,best:0,iq:0,total:0,correct:0,boosts:3,boostActive:false,fifty:false,roundCorrect:0,roundSkipped:0,roundBest:0,current:null,questionData:null,locked:false,progress:{},numProgress:{},posProgress:{},visualProgress:{},history:[]}}
function save(){localStorage.setItem(KEY,JSON.stringify(state))}
function icon(name){return ({home:'⌂',progress:'▥',chart:'▥',games:'◉',season:'▦',more:'•••',bolt:'ϟ',hash:'#',person:'♟',camera:'▣',eye:'◉',back:'‹',arrow:'›',check:'✓',close:'×',trophy:'♛',calendar:'▦'})[name]||'•'}
function slug(n){return String(n).normalize('NFKD').replace(/[’'ʿʾ]/g,'').replace(/[^a-zA-Z0-9]+/g,'-').replace(/-+/g,'-').replace(/^-|-$/g,'').toLowerCase()}
function photoCandidates(p){const s=slug(p.name),n=p.num;const remote=photoMap[p.name];return [`photos/${s}.jpg`,`photos/${s}.jpeg`,`photos/${s}.png`,`photos/${s}.webp`,`photos/${n}-${s}.jpg`,`photos/${s}-${n}.jpg`,`photos/${s}.avif`,...(remote?[remote]:[])]}
function photoHTML(p,cls='player-photo'){const cs=photoCandidates(p);return `<img class="${cls}" src="${cs[0]}" data-candidates="${esc(JSON.stringify(cs))}" data-index="0" alt="${esc(p.name)}" onerror="window.nextPhoto(this)">`}
window.nextPhoto=el=>{try{const c=JSON.parse(el.dataset.candidates),i=+el.dataset.index+1;if(i<c.length){el.dataset.index=i;el.src=c[i]}else{const d=document.createElement('div');d.className=el.className+' avatar-fallback';d.innerHTML='<span>PHOTO<br>NOT ADDED</span>';el.replaceWith(d)}}catch{}};
function mastered(obj){return Object.values(obj).filter(v=>v>=3).length}
function mastery(){return Math.round((mastered(state.progress)/Math.max(roster.length,1))*100)}
function pct(v,max){return Math.min(100,Math.round((v/Math.max(max,1))*100))}
function metric(label,v,max){return `<div class="metric"><span>${label}</span><b>${v} / ${max}</b></div>`}
function topbar(){return `<div class="topline"></div><header class="topbar"><button class="round-icon" data-nav="home">${icon('home')}</button><div class="top-title">IRISH PLAYER IQ<small>2026–27</small></div><button class="round-icon" data-nav="more">${icon('more')}</button></header>`}
function bottomNav(){const items=[['home','HOME','home'],['progress','MY PROGRESS','progress'],['games','GAMES','games'],['season','SEASON','season'],['more','MORE','more']];return `<nav class="bottom-nav">${items.map(x=>`<button class="nav-btn ${state.view===x[0]?'active':''}" data-nav="${x[0]}"><span class="nav-icon">${icon(x[2])}</span>${x[1]}</button>`).join('')}</nav>`}
function layout(body,cls='screen'){return `<div class="app-shell">${topbar()}<main class="${cls}">${body}</main>${bottomNav()}</div>`}
function home(){const m=mastery(),pm=mastered(state.progress),nm=mastered(state.numProgress),xm=mastered(state.posProgress),vm=mastered(state.visualProgress);const g=schedule.find(x=>x.status==='next')||schedule[0];return layout(`<section class="hero"><div class="irish">IRISH</div><div class="ndmark">ND</div><h1>PLAYER IQ</h1><div class="tag">KNOW THE IRISH. LIVE THE GAME.</div><div class="sync-pill">${syncStatus.status==='verified'?'✓ ROSTER VERIFIED':'ROSTER SYNC PENDING'} • ${esc((syncStatus.checked_at||'').slice(0,10))}</div><div class="hero-art"><div class="seal">ND</div></div></section><section class="iq-card"><div class="ring" style="--p:${m}%"><div class="ring-content"><b>${m}%</b><span>${m?'KEEP BUILDING':'GET STARTED'}</span></div></div><div><div class="iq-title">YOUR IRISH IQ</div>${metric('PLAYERS MASTERED',pm,roster.length)}${metric('NUMBERS MASTERED',nm,uniq(roster.map(x=>x.num)).length)}${metric('POSITIONS MASTERED',xm,uniq(roster.map(x=>x.pos)).length)}${metric('VISUAL RECOGNITION',vm,roster.length)}</div></section><section class="next-game"><div><div class="eyebrow">NEXT GAME</div><h3>${esc(g.opponent)}</h3><p>${esc(g.date)} • ${esc(g.location)}</p></div><button class="gold-btn" data-action="prep">GAME PREP →</button></section><div class="section-label">QUICK PLAY</div><div class="quick-grid">${homeMode('01','bolt','NUMBER → PLAYER','See a number, name the player.','numberPlayer')}${homeMode('02','hash','PLAYER → NUMBER','See a player, name the number.','playerNumber')}${homeMode('03','person','PLAYER → POSITION','See a player, name the position.','playerPosition')}${homeMode('04','camera','VISUAL IQ','Photo recognition practice.','photoPlayer')}</div><div class="season-mini">${mini('01','calendar','PRESEASON','Prepare for the season.')}${mini('02','bolt','PRE-GAME','Quick warm-up.')}${mini('03','check','POST-GAME','Log the result.')}${mini('04','chart','SEASON','Track the year.')}${mini('05','trophy','HISTORY','Irish football.')}</div><div class="desktop-note">Duplicate jersey numbers are intentional. Number + position identifies the player.</div>`)}
function homeMode(n,ic,title,desc,mode){return `<button class="quick-card ${n==='01'?'feature':''}" data-mode="${mode}"><div class="qnum">${n}</div><div class="qicon">${icon(ic)}</div><h3>${title}</h3><p>${desc}</p></button>`}
function mini(n,ic,title,desc){const target=title==='HISTORY'?'history':title==='SEASON'?'season':title==='PRE-GAME'?'games':'games';return `<button class="mini-card" data-nav="${target}"><div class="mi">${icon(ic)}</div><b>${title}</b><span>${desc}</span></button>`}
function games(){return layout(`<div class="page-head"><div><h1>QUICK PLAY</h1><p>Choose a mode and build your roster recall.</p></div><button class="back-btn" data-nav="home">${icon('back')} HOME</button></div><div class="mode-list">${modeRow('Mix-Up','All question types mixed. Build real roster recall.','mix','bolt',true)}${modeRow('Number → Player','See a number, name the player.','numberPlayer','bolt')}${modeRow('Player → Number','See a player, name the number.','playerNumber','hash')}${modeRow('Player → Position','See a player, name the position.','playerPosition','person')}${modeRow('Photo → Player','See a uniform photo, name the player.','photoPlayer','camera')}${modeRow('Photo → Number','See a uniform photo, name the number.','photoNumber','camera')}${modeRow('Photo → Position','See a uniform photo, name the position.','photoPosition','camera')}${modeRow('Hidden Number','Name the player and number from a masked jersey clue.','hidden','eye')}</div><div class="desktop-note">10 questions per round • 50/50 • Streak Boost • Skip</div>`)}
function modeRow(title,desc,mode,ic,feature=false){return `<button class="mode-row ${feature?'feature':''}" data-mode="${mode}"><div class="mode-icon">${icon(ic)}</div><div><div class="mode-title">${title}</div><div class="mode-desc">${desc}</div></div><div class="arrow">${icon('arrow')}</div></button>`}
function makeQuestion(type,p){const player=p||state.current;let answer,choices,label,visual=false,body='';if(type==='numberPlayer'){label='NUMBER → PLAYER';answer=player.name;choices=names(player);body=`<div class="quiz-prompt">WHO WEARS</div><div class="big-number">${esc(player.num)}</div>`}else if(type==='playerNumber'){label='PLAYER → NUMBER';answer=player.num;choices=numbers(player);body=`<div class="name-display">${esc(player.name)}</div><div class="sub-display">WHAT IS HIS JERSEY NUMBER?</div>`}else if(type==='playerPosition'){label='PLAYER → POSITION';answer=player.pos;choices=positions(player);body=`<div class="name-display">${esc(player.name)}</div><div class="sub-display">WHAT POSITION DOES HE PLAY?</div>`}else if(type==='photoPlayer'){label='PHOTO → PLAYER';answer=player.name;choices=names(player);visual=true;body=`<div class="quiz-prompt">WHO IS THIS PLAYER?</div><div class="photo-wrap">${photoHTML(player)}<div class="photo-overlay">CHOOSE YOUR ANSWER</div></div>`}else if(type==='photoNumber'){label='PHOTO → NUMBER';answer=player.num;choices=numbers(player);visual=true;body=`<div class="quiz-prompt">WHAT IS HIS JERSEY NUMBER?</div><div class="photo-wrap">${photoHTML(player)}<div class="photo-overlay">CHOOSE YOUR ANSWER</div></div>`}else if(type==='photoPosition'){label='PHOTO → POSITION';answer=player.pos;choices=positions(player);visual=true;body=`<div class="quiz-prompt">WHAT POSITION DOES HE PLAY?</div><div class="photo-wrap">${photoHTML(player)}<div class="photo-overlay">CHOOSE YOUR ANSWER</div></div>`}else if(type==='hidden'){label='HIDDEN NUMBER';answer=player.num;choices=numbers(player);visual=true;body=`<div class="quiz-prompt">WHO IS THIS PLAYER?</div><div class="photo-wrap">${photoHTML(player)}<div class="photo-overlay">JERSEY NUMBER HIDDEN</div></div><div class="hidden-number-card"><div class="mask">••</div><div class="sub-display" style="margin:4px 0 0">NAME THE NUMBER</div></div>`}return {type,label,answer,choices,player,visual,body}}
function randomPlayer(){return roster[Math.floor(Math.random()*roster.length)]}
function names(p){return shuffle([p.name,...shuffle(roster.filter(x=>x.name!==p.name).map(x=>x.name)).slice(0,3)])}
function numbers(p){return shuffle([p.num,...shuffle(uniq(roster.map(x=>x.num)).filter(x=>x!==p.num)).slice(0,3)])}
function positions(p){return shuffle([p.pos,...shuffle(uniq(roster.map(x=>x.pos)).filter(x=>x!==p.pos)).slice(0,3)])}
function chooseType(){return MODES[Math.floor(Math.random()*MODES.length)]}
function start(mode){state.view='quiz';state.gameMode=mode;state.question=0;state.round=10;state.score=0;state.streak=0;state.roundCorrect=0;state.roundSkipped=0;state.roundBest=0;state.boosts=3;state.boostActive=false;state.fifty=false;state.locked=false;state.current=randomPlayer();state.questionType=mode==='mix'?chooseType():mode;state.questionData=makeQuestion(state.questionType);render();}
function quiz(){const q=state.questionData;if(!q){state.questionData=makeQuestion(state.questionType);return quiz()}const feedback=state.locked?`<div class="feedback ${state.lastCorrect?'ok':'no'}">${state.lastCorrect?`CORRECT • +${state.lastPoints} IQ`:`NOT QUITE • STREAK RESET`}</div>`:'';const choices=q.choices.map((c,i)=>`<button class="choice ${state.choiceStates?.[i]||''} ${state.fiftyRemoved?.includes(i)?'removed':''}" data-choice="${i}" ${state.locked||state.fiftyRemoved?.includes(i)?'disabled':''}>${esc(c)}</button>`).join('');return layout(`<div class="quiz-screen"><div class="quiz-head"><button class="back-btn" data-nav="games">${icon('back')}</button><div class="mode-name"><b>${esc(q.label)}</b><span>QUESTION ${state.question+1} OF ${state.round}</span></div><div class="qstat"><strong>${state.score.toLocaleString()}</strong> SCORE<br>STREAK ${state.streak}</div></div><div class="thin-progress"><i style="width:${((state.question)/state.round)*100}%"></i></div><section class="quiz-card">${q.body}<div class="choices">${choices}</div>${feedback}<div class="quiz-tools"><button class="tool" data-action="fifty" ${state.locked||state.fifty?'disabled':''}><span>50/50</span></button><button class="tool ${state.boostActive?'active':''}" data-action="boost" ${state.locked||state.boosts===0?'disabled':''}><span>${state.boosts}</span> STREAK BOOST</button><button class="tool" data-action="skip" ${state.locked?'disabled':''}>SKIP</button></div>${state.locked?`<button class="primary-wide quiz-next" data-action="next">${state.question+1>=state.round?'SEE RESULTS':'NEXT QUESTION'} →</button>`:''}<div class="review-note">Wrong answers never reveal the player automatically.</div></section></div>`,'screen quiz-screen')}
function answer(index){if(state.locked)return;const q=state.questionData;if(!q||!q.choices[index])return;const ok=q.choices[index]===q.answer;state.locked=true;state.lastCorrect=ok;state.choiceStates={};state.choiceStates[index]=ok?'correct':'wrong';if(ok){const base=100+state.streak*25;state.lastPoints=state.boostActive?base*2:base;state.score+=state.lastPoints;state.iq+=state.lastPoints;state.streak++;state.best=Math.max(state.best,state.streak);state.roundBest=Math.max(state.roundBest,state.streak);state.roundCorrect++;state.correct++;state.progress[q.player.name]=(state.progress[q.player.name]||0)+1;if(q.type==='playerNumber'||q.type==='photoNumber'||q.type==='hidden')state.numProgress[q.player.num]=(state.numProgress[q.player.num]||0)+1;if(q.type==='playerPosition'||q.type==='photoPosition')state.posProgress[q.player.pos]=(state.posProgress[q.player.pos]||0)+1;if(q.visual)state.visualProgress[q.player.name]=(state.visualProgress[q.player.name]||0)+1;if(state.boostActive){state.boosts=Math.max(0,state.boosts-1);state.boostActive=false}}else{state.lastPoints=0;state.streak=0}state.total++;save();render()}
function next(){if(!state.locked)return;if(state.question+1>=state.round){state.view='roundComplete';state.roundResult={correct:state.roundCorrect,skipped:state.roundSkipped,score:state.score,best:state.roundBest};save();render();return}state.question++;state.current=randomPlayer();state.questionType=state.gameMode==='mix'?chooseType():state.gameMode;state.questionData=makeQuestion(state.questionType);state.locked=false;state.fifty=false;state.fiftyRemoved=[];state.choiceStates={};state.boostActive=false;save();render()}
function skip(){if(state.locked)return;state.roundSkipped++;state.streak=0;state.boostActive=false;nextSkipped()}
function nextSkipped(){if(state.question+1>=state.round){state.view='roundComplete';state.roundResult={correct:state.roundCorrect,skipped:state.roundSkipped,score:state.score,best:state.roundBest};save();render();return}state.question++;state.current=randomPlayer();state.questionType=state.gameMode==='mix'?chooseType():state.gameMode;state.questionData=makeQuestion(state.questionType);state.locked=false;state.fifty=false;state.fiftyRemoved=[];state.choiceStates={};save();render()}
function fifty(){if(state.locked||state.fifty)return;const q=state.questionData;const wrong=shuffle(q.choices.map((_,i)=>i).filter(i=>q.choices[i]!==q.answer)).slice(0,2);state.fifty=true;state.fiftyRemoved=wrong;render()}
function boost(){if(state.locked||state.boosts<=0||state.boostActive)return;state.boostActive=true;toast('Streak Boost armed • next correct answer is 2× IQ');render()}
function progress(){const tabs=[['players','PLAYERS'],['numbers','NUMBERS'],['positions','POSITIONS'],['visual','VISUAL']];let list=[];if(state.progressTab==='players')list=roster.map(p=>({p,v:state.progress[p.name]||0})).sort((a,b)=>b.v-a.v||a.p.name.localeCompare(b.p.name));if(state.progressTab==='numbers')list=uniq(roster.map(p=>p.num)).map(n=>({p:{name:`Jersey #${n}`,num:n,pos:'Number'},v:state.numProgress[n]||0}));if(state.progressTab==='positions')list=uniq(roster.map(p=>p.pos)).map(pos=>({p:{name:pos,num:'',pos},v:state.posProgress[pos]||0}));if(state.progressTab==='visual')list=roster.map(p=>({p,v:state.visualProgress[p.name]||0})).sort((a,b)=>b.v-a.v||a.p.name.localeCompare(b.p.name));const max=state.progressTab==='numbers'?uniq(roster.map(p=>p.num)).length:state.progressTab==='positions'?uniq(roster.map(p=>p.pos)).length:roster.length;const masteredCount=state.progressTab==='players'?mastered(state.progress):state.progressTab==='numbers'?mastered(state.numProgress):state.progressTab==='positions'?mastered(state.posProgress):mastered(state.visualProgress);return layout(`<div class="page-head"><div><h1>MY PROGRESS</h1><p>Build recognition one player at a time.</p></div><button class="back-btn" data-nav="home">${icon('back')} HOME</button></div><section class="progress-summary"><div class="eyebrow">YOUR IRISH IQ</div><div class="summary-grid"><div class="summary-box"><b>${state.iq.toLocaleString()}</b><span>IQ POINTS</span></div><div class="summary-box"><b>${state.best}</b><span>BEST STREAK</span></div><div class="summary-box"><b>${mastery()}%</b><span>OVERALL</span></div></div></section><div class="tabs">${tabs.map(t=>`<button class="tab ${state.progressTab===t[0]?'active':''}" data-tab="${t[0]}">${t[1]}</button>`).join('')}</div><div class="section-label">${masteredCount} MASTERED</div><div class="player-list">${list.slice(0,40).map(x=>row(x.p,x.v,state.progressTab,max)).join('')}</div></div>`)}
function row(p,v,tab,max){const name=esc(p.name),pos=esc(p.pos);return `<div class="player-row">${p.name?.startsWith('Jersey #')||!p.name?`<div class="avatar-fallback">#</div>`:photoHTML(p,'avatar')}<div><h3>${name}</h3><p>${p.num!==undefined&&p.num!==''?'#'+esc(p.num)+' • ':''}${pos}</p></div><div class="pct">${pct(v,3)}%</div></div>`}
function season(){const g=schedule.find(x=>x.status==='next')||schedule[0];return layout(`<div class="page-head"><div><h1>SEASON</h1><p>2026–27 Notre Dame schedule.</p></div><button class="back-btn" data-nav="home">${icon('back')} HOME</button></div><section class="next-game"><div><div class="eyebrow">NEXT GAME</div><h3>vs ${esc(g.opponent)}</h3><p>${esc(g.date)} • ${esc(g.location)}</p></div><button class="gold-btn" data-action="prep">GAME PREP →</button></section><div class="section-label">SCHEDULE</div><div class="schedule">${schedule.map(g=>`<div class="schedule-row"><div class="week">WK ${g.week}</div><div><h3>vs ${esc(g.opponent)}</h3><p>${esc(g.date)} • ${esc(g.location)}</p></div><div class="badge ${g.status==='next'?'next':''}">${g.status==='next'?'NEXT':'UPCOMING'}</div></div>`).join('')}</div>`)}
function more(){return layout(`<div class="page-head"><div><h1>MORE</h1><p>Settings and Irish reference.</p></div><button class="back-btn" data-nav="home">${icon('back')} HOME</button></div><div class="mode-list"><button class="mode-row" data-nav="history"><div class="mode-icon">${icon('trophy')}</div><div><div class="mode-title">HISTORY</div><div class="mode-desc">Your Irish football reference shelf.</div></div><div class="arrow">${icon('arrow')}</div></button><button class="mode-row" data-action="install"><div class="mode-icon">${icon('home')}</div><div><div class="mode-title">ADD TO HOME SCREEN</div><div class="mode-desc">Install Irish Player IQ like an app.</div></div><div class="arrow">${icon('arrow')}</div></button><button class="mode-row" data-action="reset"><div class="mode-icon">${icon('close')}</div><div><div class="mode-title">RESET ALL PROGRESS</div><div class="mode-desc">Clear local IQ, streaks and mastery.</div></div><div class="arrow">${icon('arrow')}</div></button></div>`)}
function historyView(){return layout(`<div class="page-head"><div><h1>HISTORY</h1><p>Notre Dame reference notes.</p></div><button class="back-btn" data-nav="more">${icon('back')} MORE</button></div>${history.map(h=>`<section class="gamehero"><div class="eyebrow">${esc(h.year)}</div><h2>${esc(h.title)}</h2><p>${esc(h.text)}</p></section>`).join('')}`)}
function prep(){const g=schedule.find(x=>x.status==='next')||schedule[0];return layout(`<div class="page-head"><div><h1>GAME PREP</h1><p>Warm up before ${esc(g.opponent)}.</p></div><button class="back-btn" data-nav="home">${icon('back')} HOME</button></div><section class="next-game"><div><div class="eyebrow">NEXT GAME</div><h3>vs ${esc(g.opponent)}</h3><p>${esc(g.date)} • ${esc(g.location)}</p></div><button class="gold-btn" data-mode="mix">START →</button></section><div class="mode-list">${modeRow('Quick Mix','Names, numbers and positions in one round.','mix','bolt',true)}${modeRow('Visual Warm-Up','Train recognition from uniform photos.','photoPlayer','camera')}</div>`)}
function roundComplete(){const r=state.roundResult||{correct:state.roundCorrect,skipped:state.roundSkipped,score:state.score,best:state.roundBest};const p=Math.round(r.correct/state.round*100);return layout(`<div class="page-head"><div><h1>ROUND COMPLETE</h1><p>Keep building your Irish IQ.</p></div><button class="back-btn" data-nav="games">${icon('back')} GAMES</button></div><section class="round-card"><div class="check-circle">✓</div><div class="eyebrow">MIX-UP</div><h1>${p>=80?'NICE WORK!':p>=60?'KEEP BUILDING':'GOOD START'}</h1><p>You answered ${r.correct} of ${state.round} correctly.</p><div class="round-stats"><div><b>${r.best}</b><span>LONGEST STREAK</span></div><div><b>${r.score.toLocaleString()}</b><span>ROUND IQ</span></div><div><b>${p}%</b><span>ACCURACY</span></div></div><div class="eyebrow" style="margin-bottom:4px">IRISH IQ</div><div class="levelbar"><i style="width:${Math.min(100,state.iq%1000/10)}%"></i></div><p>${r.skipped?`${r.skipped} skipped • `:''}Progress saved automatically.</p><div class="round-actions"><button class="primary-wide" data-mode="mix">PLAY AGAIN</button><button class="secondary-wide" data-nav="progress">VIEW MY PROGRESS</button></div></section>`)}
function render(){let body='';if(state.view==='home')body=home();else if(state.view==='games')body=games();else if(state.view==='quiz')body=quiz();else if(state.view==='progress')body=progress();else if(state.view==='season')body=season();else if(state.view==='more')body=more();else if(state.view==='history')body=historyView();else if(state.view==='prep')body=prep();else if(state.view==='roundComplete')body=roundComplete();$('#app').innerHTML=body;bind();save()}
function bind(){$$('[data-nav]').forEach(b=>b.onclick=()=>{state.view=b.dataset.nav;render()});$$('[data-mode]').forEach(b=>b.onclick=()=>start(b.dataset.mode));$$('[data-tab]').forEach(b=>b.onclick=()=>{state.progressTab=b.dataset.tab;render()});$$('[data-choice]').forEach(b=>b.onclick=()=>answer(+b.dataset.choice));$$('[data-action]').forEach(b=>b.onclick=()=>{const a=b.dataset.action;if(a==='next')next();if(a==='skip')skip();if(a==='fifty')fifty();if(a==='boost')boost();if(a==='prep'){state.view='prep';render()}if(a==='reset')confirmReset();if(a==='install')installHelp()});}
function confirmReset(){const el=document.createElement('div');el.className='modal-backdrop';el.innerHTML=`<div class="modal"><h2>Reset all progress?</h2><p>This clears IQ points, streaks, mastery and local quiz history on this device.</p><div class="round-actions"><button class="primary-wide" id="confirmReset">RESET</button><button class="secondary-wide" id="cancelReset">CANCEL</button></div></div>`;document.body.appendChild(el);$('#confirmReset').onclick=()=>{localStorage.removeItem(KEY);location.reload()};$('#cancelReset').onclick=()=>el.remove()}
function installHelp(){const el=document.createElement('div');el.className='modal-backdrop';el.innerHTML=`<div class="modal"><h2>Add Irish Player IQ</h2><p>On iPhone, open this page in Safari, tap Share, then choose Add to Home Screen. On Mac, use the browser's Add to Dock/Home Screen option when available.</p><div class="round-actions"><button class="primary-wide" id="closeHelp">CLOSE</button></div></div>`;document.body.appendChild(el);$('#closeHelp').onclick=()=>el.remove()}
function toast(t){const x=document.createElement('div');x.className='toast';x.textContent=t;document.body.appendChild(x);setTimeout(()=>x.remove(),1900)}
async function getJSON(file){const r=await fetch(file+'?v=autosync1',{cache:'no-store'});if(!r.ok)throw Error(file+' HTTP '+r.status);return r.json()}
async function boot(){try{[roster,schedule,history,photoMap,syncStatus]=await Promise.all([getJSON('roster.json'),getJSON('schedule.json'),getJSON('history.json'),getJSON('photo-candidates.json'),getJSON('sync-status.json')]);render();if('serviceWorker'in navigator)navigator.serviceWorker.register('sw.js?v=autosync1').catch(()=>{})}catch(e){document.body.innerHTML=`<div style="padding:30px;color:#fff;background:#031326;min-height:100vh;font-family:system-ui"><h1>Irish Player IQ</h1><p>Roster data could not load. Refresh after GitHub Pages finishes deploying.</p><pre>${esc(e.message)}</pre></div>`}}
boot();
})();
