/* Irish Player IQ — complete static/PWA build */
(() => {
  'use strict';
  const KEY='irish_iq_complete_v1';
  const DATA={roster:[],schedule:[],history:[]};
  const modes=[
    ['mix','MIX-UP','All question types mixed. Build real roster recall.','✦'],
    ['numplayer','NUMBER → PLAYER','See a jersey number and identify the Irish player.','⚡'],
    ['playernum','PLAYER → NUMBER','See the player name and recall the jersey number.','#'],
    ['playerpos','PLAYER → POSITION','Practice the player’s position along with his name.','♟'],
    ['photoPlayer','PHOTO → PLAYER','Learn to recognize the player from his uniform photo.','▣'],
    ['photoNum','PHOTO → NUMBER','See a player photo and recall his number.','▣'],
    ['photoPos','PHOTO → POSITION','See a player photo and recall his position.','▣'],
    ['hidden','HIDDEN NUMBER','Name the player and jersey number from a hidden-number challenge.','▣']
  ];
  let state=loadState();
  let currentMode='mix', current=null, locked=false, quizRound=0, roundCorrect=0, roundScore=0;
  const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
  const esc=s=>String(s).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
  const slug=s=>String(s).toLowerCase().normalize('NFKD').replace(/[^a-z0-9]+/g,'-').replace(/(^-|-$)/g,'');
  function loadState(){try{return Object.assign({score:0,streak:0,best:0,points:0,correct:0,attempts:0,players:{},numbers:{},positions:{},visual:0,theme:'dark'},JSON.parse(localStorage.getItem(KEY)||'{}'))}catch{return {score:0,streak:0,best:0,points:0,correct:0,attempts:0,players:{},numbers:{},positions:{},visual:0,theme:'dark'}}}
  function save(){localStorage.setItem(KEY,JSON.stringify(state))}
  function shuffle(a){return [...a].sort(()=>Math.random()-.5)}
  function unique(field){return [...new Set(DATA.roster.map(p=>p[field]))]}
  function playerKey(p){return `${p.num}|${p.name}|${p.pos}`}
  function ensurePlayer(p){const k=playerKey(p); state.players[k] ||= {attempts:0,correct:0,visual:0}; return state.players[k]}
  function pct(a,b){return b?Math.round(a/b*100):0}
  function masteredCount(){return DATA.roster.filter(p=>{const s=ensurePlayer(p);return s.attempts>=3&&pct(s.correct,s.attempts)>=80}).length}
  function numMastered(){return unique('num').filter(n=>{const arr=DATA.roster.filter(p=>p.num===n);return arr.every(p=>ensurePlayer(p).attempts>=2&&pct(ensurePlayer(p).correct,ensurePlayer(p).attempts)>=75)}).length}
  function posMastered(){return unique('pos').filter(pos=>{const arr=DATA.roster.filter(p=>p.pos===pos);return arr.some(p=>ensurePlayer(p).attempts>=2)}).length}
  function visualMastered(){return DATA.roster.filter(p=>ensurePlayer(p).visual>=2).length}
  function overall(){return Math.round((masteredCount()+numMastered()+posMastered()+visualMastered())/(DATA.roster.length*4)*100)}
  function photoCandidates(p){const s=slug(p.name), n=p.num; return [`photos/${s}.jpg`,`photos/${s}.jpeg`,`photos/${s}.png`,`photos/${s}.webp`,`photos/${n}-${s}.jpg`,`photos/${n}-${s}.png`,`photos/${n}-${s}.webp`,`photos/${s}-${n}.jpg`,`photos/${s}-${n}.png`,`photos/${s}-${n}.webp`]}
  function photoHTML(p,cls='player-photo'){const id='ph_'+Math.random().toString(36).slice(2);const paths=photoCandidates(p);return `<div class="${cls} photo-shell"><div class="photo-placeholder"><div class="mini-nd">ND</div><strong>${esc(p.name)}</strong><span>#${esc(p.num)} • ${esc(p.pos)}</span><small>Add uniform photo in /photos</small></div><img id="${id}" alt="${esc(p.name)} Notre Dame football"/></div>`}
  function bindPhotoFallback(root=document){root.querySelectorAll('img[id^="ph_"]').forEach((img)=>{const shell=img.closest('.photo-shell'); const name=img.alt.replace(/ Notre Dame football$/,''); const p=DATA.roster.find(x=>x.name===name); if(!p)return; const paths=photoCandidates(p); let i=0; const next=()=>{if(i>=paths.length){img.remove();return} img.src=paths[i++];}; img.onerror=next; img.onload=()=>{shell.querySelector('.photo-placeholder').style.display='none';img.style.display='block'}; next();});}
  function setView(html,nav='home'){ $('#app').innerHTML=html; $$('.nav-item').forEach(b=>b.classList.toggle('active',b.dataset.nav===nav)); bindPhotoFallback(); }
  function shell(content,nav='home',title=''){
    return `<div class="app-bg"><div class="top-gold"></div><div class="app-shell"><header class="app-top"><button class="icon-btn" data-action="home">⌂</button><div class="top-title">${title||'IRISH PLAYER IQ'}<small>2026–27</small></div><button class="icon-btn" data-action="more">•••</button></header><div id="content">${content}</div><nav class="bottom-nav"><button class="nav-item ${nav==='home'?'active':''}" data-nav="home" data-action="home"><span>⌂</span><small>HOME</small></button><button class="nav-item ${nav==='progress'?'active':''}" data-nav="progress" data-action="progress"><span>▥</span><small>MY PROGRESS</small></button><button class="nav-item ${nav==='games'?'active':''}" data-nav="games" data-action="games"><span>◉</span><small>GAMES</small></button><button class="nav-item ${nav==='season'?'active':''}" data-nav="season" data-action="season"><span>▦</span><small>SEASON</small></button><button class="nav-item ${nav==='history'?'active':''}" data-nav="history" data-action="history"><span>⋯</span><small>MORE</small></button></nav></div></div>`
  }
  function home(){
    const m=overall(); const next=DATA.schedule.find(x=>x.status==='upcoming')||DATA.schedule[0];
    setView(shell(`<section class="home-hero"><div class="nd-word">IRISH <b>ND</b></div><h1>PLAYER IQ</h1><p>KNOW THE IRISH. LIVE THE GAME.</p><div class="hero-helmet"><div class="helmet">ND</div></div></section><section class="iq-card"><div class="ring" style="--p:${m*3.6}deg"><div><b>${m}%</b><small>KEEP IT GOING!</small></div></div><div class="iq-lines"><h3>YOUR IRISH IQ</h3><div><span>PLAYERS MASTERED</span><b>${masteredCount()} / ${DATA.roster.length}</b></div><div><span>NUMBERS MASTERED</span><b>${numMastered()} / ${unique('num').length}</b></div><div><span>POSITIONS MASTERED</span><b>${posMastered()} / ${unique('pos').length}</b></div><div><span>VISUAL RECOGNITION</span><b>${visualMastered()} / ${DATA.roster.length}</b></div></div></section><section class="next-game"><div><small>NEXT GAME</small><h2>vs ${esc(next.opponent)}</h2><p>${esc(next.date)} • ${esc(next.time)}<br>${esc(next.venue)}</p></div><button class="gold-btn" data-action="pregame">GAME PREP →</button></section><section><div class="section-head"><h2>CHOOSE YOUR MODE</h2></div><div class="mode-grid home-modes">${[['games','⚡','QUICK PLAY','NUMBER → PLAYER'],['games','▦','ROSTER CHALLENGE','PLAYER → NUMBER'],['games','▣','VISUAL IQ','PHOTO → PLAYER'],['games','▣','ELITE MODE','HIDDEN NUMBER'],['season','♟','PRESEASON','Preview the season'],['season','▦','SEASON','2026 TRACKER'],['history','♜','HISTORY','Explore Irish history'],['more','▦','MORE','Settings & more']].map(x=>`<button class="tile" data-action="${x[0]}" ${x[0]==='games'?'':''}><span class="tile-icon">${x[1]}</span><b>${x[2]}</b><small>${x[3]}</small></button>`).join('')}</div></section>`, 'home'));
  }
  function statsStrip(){return `<div class="stats-strip"><div><b>${state.score}</b><small>SCORE</small></div><div><b>${state.streak}</b><small>STREAK</small></div><div><b>${state.best}</b><small>BEST</small></div><div><b>${state.points.toLocaleString()}</b><small>POINTS</small></div></div>`}
  function games(){setView(shell(`<section class="screen-heading"><small>QUICK PLAY</small><h1>CHOOSE A MODE</h1><p>Train the exact skills you want to remember.</p></section>${statsStrip()}<div class="game-mode-list">${modes.map((m,i)=>`<button class="game-mode ${i===0?'selected':''}" data-mode="${m[0]}" data-action="startMode"><span>${m[3]}</span><div><b>${String(i+1).padStart(2,'0')} • ${m[1]}</b><small>${m[2]}</small></div><em>›</em></button>`).join('')}</div><div class="tip-card"><b>PRO TIP</b><span>Duplicate jersey numbers are intentional. A number alone never identifies a player.</span></div>`, 'games','GAMES')); bindModeButtons()}
  function bindModeButtons(){$$('.game-mode').forEach(b=>b.addEventListener('click',()=>startMode(b.dataset.mode)))}
  function makeQuestion(mode){
    const p=DATA.roster[Math.floor(Math.random()*DATA.roster.length)];
    let type=mode; if(mode==='mix'){type=shuffle(['numplayer','playernum','playerpos','photoPlayer','photoNum','photoPos','hidden'])[0]}
    let title='',sub='',answer='',choices=[];
    if(type==='numplayer'||type==='hidden'){title=type==='hidden'?'WHO IS THIS PLAYER?':`WHO WEARS #${p.num}?`;sub=type==='hidden'?'Identify the player — then recall the hidden number.':`NUMBER → PLAYER • POSITION: ${p.pos}`;answer=p.name;choices=choiceNames(p)}
    if(type==='playernum'){title=p.name;sub='WHAT IS HIS JERSEY NUMBER?';answer=p.num;choices=choiceNumbers(p.num)}
    if(type==='playerpos'){title=p.name;sub='WHAT POSITION DOES HE PLAY?';answer=p.pos;choices=choicePositions(p.pos)}
    if(type==='photoPlayer'||type==='photoNum'||type==='photoPos'){title=type==='photoPlayer'?'WHO IS THIS PLAYER?':type==='photoNum'?'WHAT IS HIS JERSEY NUMBER?':'WHAT POSITION DOES HE PLAY?';sub='VISUAL IQ • STUDY THE UNIFORM';answer=type==='photoPlayer'?p.name:type==='photoNum'?p.num:p.pos;choices=type==='photoPlayer'?choiceNames(p):type==='photoNum'?choiceNumbers(p.num):choicePositions(p.pos)}
    return {p,type,title,sub,answer,choices};
  }
  function choiceNames(p){return shuffle([p.name,...shuffle(DATA.roster.filter(x=>x.name!==p.name).map(x=>x.name)).slice(0,3)])}
  function choiceNumbers(n){return shuffle([n,...shuffle(unique('num').filter(x=>x!==n)).slice(0,3)])}
  function choicePositions(pos){return shuffle([pos,...shuffle(unique('pos').filter(x=>x!==pos)).slice(0,3)])}
  function quiz(mode){currentMode=mode; quizRound=0;roundCorrect=0;roundScore=0;nextQuestion();}
  function nextQuestion(){locked=false;quizRound++;current=makeQuestion(currentMode); const p=current.p; const photo=current.type.startsWith('photo')||current.type==='hidden'; setView(shell(`<section class="quiz-head"><button class="back-link" data-action="games">‹</button><div><b>${current.type==='mix'?'MIX-UP':labelFor(current.type)}</b><small>QUESTION ${Math.min(quizRound,10)} OF 10</small></div><div class="quiz-mini"><span>STREAK<br><b>${state.streak}</b></span><span>SCORE<br><b>${state.points.toLocaleString()}</b></span></div></section><div class="quiz-progress"><i style="width:${Math.min(quizRound-1,10)*10}%"></i></div><section class="question-card">${photo?photoHTML(p):''}<div class="question-copy"><small>${esc(current.sub)}</small><h1>${esc(current.title)}</h1>${current.type==='hidden'?`<div class="hidden-number">??</div>`:''}<p>CHOOSE YOUR ANSWER</p></div><div class="answers">${current.choices.map((c,i)=>`<button class="answer" data-index="${i}">${esc(c)}</button>`).join('')}</div><div class="quiz-tools"><button data-action="fifty">50/50</button><span class="boost">${state.streak%3===0&&state.streak>0?'3':''}</span><b>STREAK BOOST</b><button data-action="skip">SKIP</button></div><div id="quiz-result"></div></section>`, 'games', current.type==='mix'?'MIX-UP':labelFor(current.type))); bindQuiz();}
  function labelFor(t){return ({numplayer:'NUMBER → PLAYER',playernum:'PLAYER → NUMBER',playerpos:'PLAYER → POSITION',photoPlayer:'VISUAL IQ',photoNum:'PHOTO → NUMBER',photoPos:'PHOTO → POSITION',hidden:'ELITE MODE'})[t]||'QUIZ'}
  function bindQuiz(){$$('.answer').forEach(b=>b.addEventListener('click',()=>answer(Number(b.dataset.index)))); $('[data-action="fifty"]')?.addEventListener('click',fifty); $('[data-action="skip"]')?.addEventListener('click',()=>{state.streak=0;save();nextQuestion()});}
  function answer(i){if(locked)return;locked=true;const picked=current.choices[i],correct=picked===current.answer;const p=current.p;const s=ensurePlayer(p);s.attempts++;state.attempts++; if(correct){s.correct++;state.correct++;state.score++;state.streak++;state.best=Math.max(state.best,state.streak);let pts=100+(state.streak*25);if(current.type.startsWith('photo')){s.visual++;state.visual++} if(state.streak%5===0)pts+=250;state.points+=pts;roundCorrect++;roundScore+=pts;} else {state.streak=0;} if(current.type==='playernum') state.numbers[p.num]=(state.numbers[p.num]||0)+(correct?1:0); if(current.type==='playerpos') state.positions[p.pos]=(state.positions[p.pos]||0)+(correct?1:0); save(); $$('.answer').forEach((b,idx)=>{b.disabled=true;if(idx===i)b.classList.add(correct?'good':'bad');if(b.textContent.trim()===current.answer)b.classList.add('good')}); $('#quiz-result').innerHTML=`<div class="answer-result ${correct?'correct':'wrong'}"><strong>${correct?'✓ CORRECT':'✕ NOT QUITE'}</strong><span>${esc(p.name)} • #${esc(p.num)} • ${esc(p.pos)}</span><b>${correct?'+'+(100+state.streak*25):'0'} IQ POINTS</b></div><button class="gold-btn full" id="continueQ">${quizRound>=10?'ROUND COMPLETE':'NEXT QUESTION'} →</button>`; $('#continueQ').onclick=()=>quizRound>=10?roundComplete():nextQuestion()}
  function fifty(){if(locked)return;const wrong=$$('.answer').filter(b=>b.textContent.trim()!==current.answer);shuffle(wrong).slice(0,2).forEach(b=>{b.disabled=true;b.classList.add('faded')})}
  function roundComplete(){setView(shell(`<section class="complete"><div class="big-check">✓</div><small>ROUND COMPLETE</small><h1>NICE WORK!</h1><p>You answered <b>${roundCorrect}</b> of 10 correctly.</p><div class="complete-stats"><div><b>${state.best}</b><small>LONGEST STREAK</small></div><div><b>${roundScore.toLocaleString()}</b><small>ROUND SCORE</small></div><div><b>${state.points.toLocaleString()}</b><small>TOTAL IQ POINTS</small></div></div><div class="level"><span>IRISH IQ</span><b>${Math.min(99,Math.floor(state.points/500)+1)}</b></div><button class="gold-btn full" data-action="games">CONTINUE</button></section>`, 'games','RESULTS'));}
  function progress(){const tabs=['players','numbers','positions','visual'];setView(shell(`<section class="screen-heading"><small>MY PROGRESS</small><h1>YOUR IRISH IQ</h1><p>Track the players and skills you have actually learned.</p></section><div class="progress-overview"><div class="ring big" style="--p:${overall()*3.6}deg"><div><b>${overall()}%</b><small>LEARNED</small></div></div><div><div class="meter-row"><span>PLAYERS MASTERED</span><b>${masteredCount()} / ${DATA.roster.length}</b></div><div class="meter-row"><span>NUMBERS MASTERED</span><b>${numMastered()} / ${unique('num').length}</b></div><div class="meter-row"><span>POSITIONS MASTERED</span><b>${posMastered()} / ${unique('pos').length}</b></div><div class="meter-row"><span>VISUAL RECOGNITION</span><b>${visualMastered()} / ${DATA.roster.length}</b></div></div></div><div class="tabs">${tabs.map(t=>`<button class="tab ${t==='players'?'active':''}" data-tab="${t}">${t.toUpperCase()}</button>`).join('')}</div><div id="progress-list"></div>`, 'progress','MY PROGRESS')); renderProgress('players');$$('.tab').forEach(b=>b.onclick=()=>{$$('.tab').forEach(x=>x.classList.remove('active'));b.classList.add('active');renderProgress(b.dataset.tab)})}
  function renderProgress(tab){let list=''; if(tab==='players'||tab==='visual'){list=DATA.roster.map(p=>{const s=ensurePlayer(p);const n=pct(s.correct,s.attempts);return {p,s,n}}).filter(x=>tab==='visual'?x.s.visual>0:x.s.attempts>0).sort((a,b)=>b.n-a.n).slice(0,30).map(x=>`<button class="progress-player" data-action="profile" data-player="${esc(playerKey(x.p))}">${photoHTML(x.p,'tiny-photo')}<div><b>${esc(x.p.name)}</b><small>#${esc(x.p.num)} • ${esc(x.p.pos)}</small><em>${x.n}%</em></div></button>`).join('');}
    if(tab==='numbers'){list=unique('num').map(n=>{const arr=DATA.roster.filter(p=>p.num===n);const attempts=arr.reduce((a,p)=>a+ensurePlayer(p).attempts,0);return `<div class="data-row"><b>#${n}</b><span>${arr.map(p=>p.name).join(' / ')}</span><em>${attempts} attempts</em></div>`}).join('')}
    if(tab==='positions'){list=unique('pos').map(pos=>`<div class="data-row"><b>${pos}</b><span>${DATA.roster.filter(p=>p.pos===pos).length} roster entries</span><em>${DATA.roster.filter(p=>p.pos===pos).reduce((a,p)=>a+ensurePlayer(p).correct,0)} correct</em></div>`).join('')}
    $('#progress-list').innerHTML=`<div class="progress-list">${list||'<div class="empty">Start playing to build your progress.</div>'}</div>`;bindPhotoFallback();$$('[data-action="profile"]').forEach(b=>b.onclick=()=>profile(b.dataset.player));}
  function profile(key){const p=DATA.roster.find(x=>playerKey(x)===key);if(!p)return;const s=ensurePlayer(p);setView(shell(`<section class="profile"><button class="back-link" data-action="progress">‹</button>${photoHTML(p,'profile-photo')}<div class="profile-number">${p.num}</div><h1>${esc(p.name)}</h1><h3>${esc(p.pos)}</h3><div class="profile-facts"><div><b>${s.attempts}</b><small>ATTEMPTS</small></div><div><b>${pct(s.correct,s.attempts)}%</b><small>ACCURACY</small></div><div><b>${s.visual}</b><small>VISUAL</small></div></div><div class="profile-copy"><b>ABOUT</b><p>Use the quiz repeatedly until the name, number, position and face become automatic.</p></div></section>`, 'progress','PLAYER PROFILE'))}
  function season(){setView(shell(`<section class="screen-heading"><small>2026 SEASON</small><h1>TRACK THE SEASON</h1><p>Schedule, results and game-prep tools.</p></section><div class="season-card"><div><small>RECORD</small><b>1–0</b></div><div><small>ACC</small><b>0–0</b></div></div><div class="schedule-tabs"><button class="active">SCHEDULE</button><button>STANDINGS</button></div><div class="schedule-list">${DATA.schedule.map(g=>`<div class="schedule-row"><div><b>${esc(g.date)}</b><span>vs ${esc(g.opponent)}</span></div><div><b class="${g.status==='final'?'win':''}">${esc(g.result||g.time)}</b><small>${esc(g.venue)}</small></div></div>`).join('')}</div><button class="gold-btn full">FULL SCHEDULE</button>`, 'season','SEASON'))}
  function pregame(){const g=DATA.schedule.find(x=>x.status==='upcoming')||DATA.schedule[0];setView(shell(`<section class="pregame"><button class="back-link" data-action="home">‹</button><small>PRE-GAME</small><h1>SCOUT THE MATCHUP</h1><div class="matchup"><div><div class="nd-large">ND</div><b>#12 NOTRE DAME</b><small>1–0</small></div><strong>VS</strong><div><div class="opp-badge">W</div><b>${esc(g.opponent.toUpperCase())}</b><small>0–1</small></div></div><div class="game-details"><div>▣ <span>${esc(g.date)}, 2026</span></div><div>◷ <span>${esc(g.time)}</span></div><div>⌖ <span>${esc(g.venue)}</span></div><div>▣ <span>${esc(g.network)}</span></div></div><button class="gold-btn full" data-action="games">START GAME PREP</button></section>`, 'season','PRE-GAME'))}
  function postgame(){setView(shell(`<section class="postgame"><small>POST-GAME</small><h1>GAME RECAP</h1><div class="scoreboard"><div>ND<br><b>34</b></div><strong>FINAL</strong><div>WIS<br><b>21</b></div></div>${['GAME SUMMARY','INDIVIDUAL PERFORMANCE','STAT LEADERS','QUIZ','YOUR PREDICTIONS'].map((x,i)=>`<button class="recap-row"><span>${['◉','♟','#','▤','☁'][i]}</span><div><b>${x}</b><small>${['Key moments & stats','Top individual performances','Who led the Irish?','Test what you know','See how you did'][i]}</small></div><em>→</em></button>`).join('')}<button class="gold-btn full" data-action="games">PLAY POST-GAME QUIZ</button></section>`, 'season','POST-GAME'))}
  function history(){setView(shell(`<section class="screen-heading"><small>HISTORY MODE</small><h1>EXPLORE THE LEGACY</h1><p>Great teams, great coaches and the players who made Notre Dame football.</p></section><div class="era-list">${DATA.history.map((h,i)=>`<button class="era" data-era="${i}"><div class="era-photo">${['1890','ROCK','1940','1973','88'][i]}</div><div><b>${esc(h.era)}</b><small>${esc(h.years)}</small></div><em>›</em></button>`).join('')}</div><button class="gold-btn full">VIEW ALL ERAS</button><section class="legend-card"><small>LEARN THE LEGENDS</small><h2>JOE MONTANA</h2><p>QB • 1977–1979 • JERSEY #3</p><button class="gold-btn">TEST YOUR KNOWLEDGE</button></section>`, 'history','HISTORY'))}
  function more(){setView(shell(`<section class="screen-heading"><small>MORE</small><h1>SETTINGS & TOOLS</h1></section><div class="settings-list"><button data-action="reset"><b>RESET MY IQ</b><small>Clear score, streak and mastery data.</small><span>›</span></button><button><b>PHOTO GUIDE</b><small>Use photos named player-name.jpg in /photos.</small><span>›</span></button><button><b>INSTALL APP</b><small>Use Safari Share → Add to Home Screen.</small><span>›</span></button><button><b>DATA</b><small>${DATA.roster.length} roster entries loaded locally.</small><span>›</span></button></div><div class="trust"><b>ACCURATE. VERIFIED. TRUSTED.</b><p>This build keeps roster data local and treats duplicate jersey numbers as intentional. Verify roster changes before using the app as an official reference.</p></div>`, 'history','MORE'))}
  function reset(){if(confirm('Reset your Irish Player IQ progress?')){localStorage.removeItem(KEY);state=loadState();home()}}
  function route(action){({home,games,progress,season,history,more,pregame,postgame,reset}[action]||home)()}
  function startMode(m){quiz(m)}
  document.addEventListener('click',e=>{const b=e.target.closest('[data-action]');if(!b)return;const a=b.dataset.action;if(a==='startMode'||a==='fifty'||a==='skip')return;route(a)});
  async function init(){try{DATA.roster=await fetch('roster.json').then(r=>r.json());DATA.schedule=await fetch('schedule.json').then(r=>r.json());DATA.history=await fetch('history.json').then(r=>r.json());home();if('serviceWorker' in navigator)navigator.serviceWorker.register('sw.js').catch(()=>{});}catch(err){document.body.innerHTML='<pre style="padding:30px;color:white;background:#06182b">Irish Player IQ could not load its local data. Check that roster.json, schedule.json and history.json are in the repository root.</pre>';console.error(err)}}
  init();
})();
